services:
  api:
    container_name: demo_test_api
    environment: 
      - DB_NAME=habitrabbits #this is very important in order to connect to mongo
      - DB_CONNECTION=mongodb://billie:habitpass@db:27017
    depends_on:
      - db
    tty: true
  db:
    container_name: demo_test_db
    volumes:
      - "test_db:/var/lib/mongodb/data"
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=billie
      - MONGO_INITDB_DATABASE=habitrabbits
      - MONGO_INITDB_ROOT_PASSWORD=habitpass
volumes:
  test_db:
networks: 
  default:
    name: demo_app_test
